### ISSUE TITLE
A user can view potential members

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/Member-Meeter#1]
**Motivation**
To allow bands of all styles to easily find members who fit their needs.

**Wireframe**
<img src="https://occs.mybalsamiq.com/mockups/6463023.png?key=c55967a3fa704d732af98e150bb34de7702e8098"
alt= "wireframe" />

**Data Model**

Fetched Data

```javascript
{"page":1,"per_page":3,"total":12,"total_pages":4,"data":[{"id":1,"first_name":"George","last_name":"Bluth","avatar":"https://s3.amazonaws.com/uifaces/faces/twitter/calebogden/128.jpg"}
```

JS Data
```javascript
var musicians = [
 {
  firstName: "George", 
  lastName: "Bluth", 
  photo: "https://s3.amazonaws.com/uifaces/faces/twitter/calebogden/128.jpg", 
  id: 1
}
]
```

***Component Hierarchy***
```javascript
<Musicians>
  <Musician>
    <MusicianDetails Location Instruments/>
  </Musician>
</Musicians>
```

**Tasks**
- [x]  Create a wireframe.
- [x]  Set up application environment.
- [x]  Use "fetch" to acquire musician data.
- [x] Render data to "DOM" using "React".
- [x] Style data with "bootstrap" into cards.

**Comment by anthonyrodarte** [comment]
**Layout matches wireframe.**

<img src="https://gyazo.com/fb0de43d1d6400c046c8ef282a375db5"
alt= "Application Screenshot" />
