### ISSUE TITLE
A user can see musician details.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/Member-Meeter#5]
**Wireframe**

![screen shot 2018-04-04 at 1 24 17 pm](https://user-images.githubusercontent.com/22861295/38332739-8891ba26-380b-11e8-9fa8-73d784f0e673.png)

***Component Hierarchy***

```javascript
<Musicians>
  <Musician>
    <MusicianCard>
       <MusicianDetails />
    </MusicianCard>
  </Musician>
</Musicians>
```

**Tasks**

- [x]  Build static modal.
- [x]  Style modal.
- [x] Modal is hidden until card is clicked.
- [x]  Populate modal with selected musician info.
