### ISSUE TITLE
A user can see the musicians location on a map.

### ISSUE THREAD

**Issue by anthonyrodarte** [anthonyrodarte/Member-Meeter#7]
**Wireframe**

![screen shot 2018-04-06 at 9 41 58 am](https://user-images.githubusercontent.com/22861295/38433470-d89b4a62-397f-11e8-9530-188656a6b98a.png)

**Component Hierarchy**
``` javascript

<Musician>
  <Musician Details>
    <Map />
  </ Musician Details>
</ Musician
```

**Tasks**

- [x] Build Static Map.
- [x] Map Centers Around Musician Location.
- [x] Add marker to map.
